# These are supported funding model platforms

github: [anibalealvarezs]
# patreon: # Replace with your patreon username
# open_collective: # Replace with your open_collective username
# ko_fi: # Replace with your ko_fi username
# tidelift: # Replace with your tidelift platform/package-name e.g., npm/babel
# custom: ['https://paypal.me/anibalealvarezs']
