shopify:
  enabled: true
  shopify_api_key: # api_key
  shopify_shop_name: # shop_name
  shopify_last_stable_revision: 2024-04
klaviyo:
  enabled: true
  klaviyo_api_key: # api_key
  metrics:
    - Added to Cart
    - Placed Order
    - Opened Email
  metrics_cache_ttl: 86400
bigcommerce:
  # bigcommerce_client_id: # client_id
  # bigcommerce_client_secret: # client_secret
  bigcommerce_access_token: # access_token
  bigcommerce_store_hash: # store_hash
netsuite:
  enabled: true
  netsuite_consumer_id: # consumer_id
  netsuite_consumer_secret: # consumer_secret
  netsuite_token_id: # token_id
  netsuite_token_secret: # token_secret
  netsuite_account_id: # account_id
  netsuite_store: #netsuite_store
  netsuite_store_base_url: #netsuite_store_base_url
amazon_ads:
  enabled: false
  ads_client_id: # sheets_client_id
  ads_client_secret: # sheets_client_secret
  ads_redirect_uri: https://chmwmedia.postman.co
  ads_refresh_token: # sheets_refresh_token
  sheets_scope: [ advertising::campaign_management ]
  ads_token: # token_string
  ads_profile_id: # 358923519404264
facebook:
  # TOKENS
  fb_graph_user_access_token: #fb_graph_user_access_token
  fb_graph_page_access_token: #fb_graph_page_access_token
  fb_graph_app_access_token: #fb_graph_app_access_token
  fb_graph_client_access_token: #fb_graph_client_access_token
  # OPTIONAL TOKENS
  fb_graph_long_lived_user_access_token: #fb_graph_long_lived_user_access_token
  fb_graph_long_lived_page_access_token: #fb_graph_long_lived_page_access_token
  fb_graph_long_lived_client_access_token: #fb_graph_long_lived_client_access_token
  # APP CREDENTIALS
  fb_user_id: #fb_user_id
  fb_app_id: #fb_app_id
  fb_app_secret: #fb_app_secret
  fb_app_redirect_uri: https://oauth.pstmn.io/v1/browser-callback
google:
  client_id: #client_id
  client_secret: #client_secret
  redirect_uri: https://oauth.pstmn.io/v1/browser-callback
  refresh_token: #refresh_token
  user_id: #your@email.com
  token_path: #./config/google_tokens.json
google_search_console:
  enabled: true
  scope: https://www.googleapis.com/auth/webmasters # can be a comma-separated list
  token: #token
  # The following fields are optional and override the global 'google' settings if provided
  # client_id: #specific_client_id
  # client_secret: #specific_client_secret
  # refresh_token: #specific_refresh_token
  # user_id: #specific_user_id
  # token_path: #specific_token_path
  test_site_url: #sc-domain:anibalalvarez.com
  test_removable_site_url: #sc-domain:loquesea.com
  test_sitemap_url: #https://anibalalvarez.com/sitemap_index.xml
  test_removable_sitemap_url: #https://anibalalvarez.com/geo-sitemap.xml
  test_inspect_url: #https://anibalalvarez.com/ecommerce-conversion-optimization-businesses/
  sites:
    - url: #"sc-domain:anibalalvarez.com"
      title: #"Anibal Alvarez"
      hostname: #"anibalalvarez.com"
      include_keywords: [] # operator: CONTAINS / supports just one keyword at a time at the moment / if not set, all keywords will be included
      exclude_keywords: [] # operator: NOT_CONTAINS / If not set, all keywords will be included / if include_keywords is set, exclude_keywords will be ignored
      include_countries: [] # operator: EQUALS / supports just one country at a time at the moment / if not set, all countries will be included
      exclude_countries: [] # operator: NOT_EQUALS / if not set, all countries will be included / if include_countries is set, exclude_countries will be ignored
      include_pages: [] # operator: CONTAINS / supports just one keyword at a time at the moment / if not set, all keywords will be included
      exclude_pages: [] # operator: NOT_CONTAINS / If not set, all keywords will be included / if include_keywords is set, exclude_keywords will be ignored
      target_countries: [] # Any country not in this list will be grouped as "other" / if not set, no country will be grouped
      target_keywords: [] # Any keyword not containing any of these keywords will be grouped as "other" / if not set, no keyword will be grouped
      enabled: true
  metrics:
  metrics_cache_ttl: 86400

