shopify:
  enabled: true
  shopify_api_key: # api_key
  shopify_shop_name: # shop_name
  shopify_last_stable_revision: 2024-04
klaviyo:
  enabled: false
  klaviyo_api_key: # api_key
bigcommerce:
  # bigcommerce_client_id: # client_id
  # bigcommerce_client_secret: # client_secret
  bigcommerce_access_token: # access_token
  bigcommerce_store_hash: # store_hash
netsuite:
  enabled: true
  netsuite_consumer_id: # consumer_id
  netsuite_consumer_secret: # consumer_secret
  netsuite_token_id: # token_id
  netsuite_token_secret: # token_secret
  netsuite_account_id: # account_id
amazon_ads:
  enabled: false
  ads_client_id: # sheets_client_id
  ads_client_secret: # sheets_client_secret
  ads_redirect_uri: https://chmwmedia.postman.co
  ads_refresh_token: # sheets_refresh_token
  sheets_scope: [ advertising::campaign_management ]
  ads_token: # token_string
  ads_profile_id: # 358923519404264
