<?php

namespace Enums;

enum CampaignObjective: string
{
    case APP_INSTALLS = 'APP_INSTALLS';
    case BRAND_AWARENESS = 'BRAND_AWARENESS';
    case CONVERSIONS = 'CONVERSIONS';
    case LEAD_GENERATION = 'LEAD_GENERATION';
    case LINK_CLICKS = 'LINK_CLICKS';
    case MESSAGES = 'MESSAGES';
    case PAGE_LIKES = 'PAGE_LIKES';
    case POST_ENGAGEMENT = 'POST_ENGAGEMENT';
    case REACH = 'REACH';
    case STORE_TRAFFIC = 'STORE_TRAFFIC';
    case VIDEO_VIEWS = 'VIDEO_VIEWS';
    case CATALOG_SALES = 'CATALOG_SALES';
    case EVENT_RESPONSES = 'EVENT_RESPONSES';
    case PRODUCT_CATALOG_SALES = 'PRODUCT_CATALOG_SALES';
    case TRAFFIC = 'TRAFFIC';
    case ENGAGEMENT = 'ENGAGEMENT';
    case SALES = 'SALES';
    case OUTCOME_ENGAGEMENT = 'OUTCOME_ENGAGEMENT';
    case OUTCOME_CONVERSIONS = 'OUTCOME_CONVERSIONS';
    case OUTCOME_TRAFFIC = 'OUTCOME_TRAFFIC';
    case OUTCOME_AWARENESS = 'OUTCOME_AWARENESS';
    case OUTCOME_LEADS = 'OUTCOME_LEADS';
    case OUTCOME_SALES = 'OUTCOME_SALES';
    case OUTCOME_APP_PROMOTION = 'OUTCOME_APP_PROMOTION';
}
