<?php

namespace Enums;

enum Country: string
{
    case ABW = 'ABW'; // Aruba
    case AFG = 'AFG'; // Afghanistan
    case AGO = 'AGO'; // Angola
    case AIA = 'AIA'; // Anguilla
    case ALA = 'ALA'; // Åland Islands
    case ALB = 'ALB'; // Albania
    case AND = 'AND'; // Andorra
    case ARE = 'ARE'; // United Arab Emirates
    case ARG = 'ARG'; // Argentina
    case ARM = 'ARM'; // Armenia
    case ASM = 'ASM'; // American Samoa
    case ATA = 'ATA'; // Antarctica
    case ATF = 'ATF'; // French Southern Territories
    case ATG = 'ATG'; // Antigua and Barbuda
    case AUS = 'AUS'; // Australia
    case AUT = 'AUT'; // Austria
    case AZE = 'AZE'; // Azerbaijan
    case BDI = 'BDI'; // Burundi
    case BEL = 'BEL'; // Belgium
    case BEN = 'BEN'; // Benin
    case BES = 'BES'; // Bonaire, Sint Eustatius and Saba
    case BFA = 'BFA'; // Burkina Faso
    case BGD = 'BGD'; // Bangladesh
    case BGR = 'BGR'; // Bulgaria
    case BHR = 'BHR'; // Bahrain
    case BHS = 'BHS'; // Bahamas
    case BIH = 'BIH'; // Bosnia and Herzegovina
    case BLM = 'BLM'; // Saint Barthélemy
    case BLR = 'BLR'; // Belarus
    case BLZ = 'BLZ'; // Belize
    case BMU = 'BMU'; // Bermuda
    case BOL = 'BOL'; // Bolivia
    case BRA = 'BRA'; // Brazil
    case BRB = 'BRB'; // Barbados
    case BRN = 'BRN'; // Brunei Darussalam
    case BTN = 'BTN'; // Bhutan
    case BVT = 'BVT'; // Bouvet Island
    case BWA = 'BWA'; // Botswana
    case CAF = 'CAF'; // Central African Republic
    case CAN = 'CAN'; // Canada
    case CCK = 'CCK'; // Cocos (Keeling) Islands
    case CHE = 'CHE'; // Switzerland
    case CHL = 'CHL'; // Chile
    case CHN = 'CHN'; // China
    case CIV = 'CIV'; // Côte d'Ivoire
    case CMR = 'CMR'; // Cameroon
    case COD = 'COD'; // Congo, Democratic Republic of the
    case COG = 'COG'; // Congo
    case COK = 'COK'; // Cook Islands
    case COL = 'COL'; // Colombia
    case COM = 'COM'; // Comoros
    case CPV = 'CPV'; // Cabo Verde
    case CRI = 'CRI'; // Costa Rica
    case CUB = 'CUB'; // Cuba
    case CUW = 'CUW'; // Curaçao
    case CXR = 'CXR'; // Christmas Island
    case CYM = 'CYM'; // Cayman Islands
    case CYP = 'CYP'; // Cyprus
    case CZE = 'CZE'; // Czechia
    case DEU = 'DEU'; // Germany
    case DJI = 'DJI'; // Djibouti
    case DMA = 'DMA'; // Dominica
    case DNK = 'DNK'; // Denmark
    case DOM = 'DOM'; // Dominican Republic
    case DZA = 'DZA'; // Algeria
    case ECU = 'ECU'; // Ecuador
    case EGY = 'EGY'; // Egypt
    case ERI = 'ERI'; // Eritrea
    case ESH = 'ESH'; // Western Sahara
    case ESP = 'ESP'; // Spain
    case EST = 'EST'; // Estonia
    case ETH = 'ETH'; // Ethiopia
    case FIN = 'FIN'; // Finland
    case FJI = 'FJI'; // Fiji
    case FLK = 'FLK'; // Falkland Islands (Malvinas)
    case FRA = 'FRA'; // France
    case FRO = 'FRO'; // Faroe Islands
    case FSM = 'FSM'; // Micronesia
    case GAB = 'GAB'; // Gabon
    case GBR = 'GBR'; // United Kingdom
    case GEO = 'GEO'; // Georgia
    case GGY = 'GGY'; // Guernsey
    case GHA = 'GHA'; // Ghana
    case GIB = 'GIB'; // Gibraltar
    case GIN = 'GIN'; // Guinea
    case GLP = 'GLP'; // Guadeloupe
    case GMB = 'GMB'; // Gambia
    case GNB = 'GNB'; // Guinea-Bissau
    case GNQ = 'GNQ'; // Equatorial Guinea
    case GRC = 'GRC'; // Greece
    case GRD = 'GRD'; // Grenada
    case GRL = 'GRL'; // Greenland
    case GTM = 'GTM'; // Guatemala
    case GUF = 'GUF'; // French Guiana
    case GUM = 'GUM'; // Guam
    case GUY = 'GUY'; // Guyana
    case HKG = 'HKG'; // Hong Kong
    case HMD = 'HMD'; // Heard Island and McDonald Islands
    case HND = 'HND'; // Honduras
    case HRV = 'HRV'; // Croatia
    case HTI = 'HTI'; // Haiti
    case HUN = 'HUN'; // Hungary
    case IDN = 'IDN'; // Indonesia
    case IMN = 'IMN'; // Isle of Man
    case IND = 'IND'; // India
    case IOT = 'IOT'; // British Indian Ocean Territory
    case IRL = 'IRL'; // Ireland
    case IRN = 'IRN'; // Iran
    case IRQ = 'IRQ'; // Iraq
    case ISL = 'ISL'; // Iceland
    case ISR = 'ISR'; // Israel
    case ITA = 'ITA'; // Italy
    case JAM = 'JAM'; // Jamaica
    case JEY = 'JEY'; // Jersey
    case JOR = 'JOR'; // Jordan
    case JPN = 'JPN'; // Japan
    case KAZ = 'KAZ'; // Kazakhstan
    case KEN = 'KEN'; // Kenya
    case KGZ = 'KGZ'; // Kyrgyzstan
    case KHM = 'KHM'; // Cambodia
    case KIR = 'KIR'; // Kiribati
    case KNA = 'KNA'; // Saint Kitts and Nevis
    case KOR = 'KOR'; // Korea, Republic of
    case KWT = 'KWT'; // Kuwait
    case LAO = 'LAO'; // Lao People's Democratic Republic
    case LBN = 'LBN'; // Lebanon
    case LBR = 'LBR'; // Liberia
    case LBY = 'LBY'; // Libya
    case LCA = 'LCA'; // Saint Lucia
    case LIE = 'LIE'; // Liechtenstein
    case LKA = 'LKA'; // Sri Lanka
    case LSO = 'LSO'; // Lesotho
    case LTU = 'LTU'; // Lithuania
    case LUX = 'LUX'; // Luxembourg
    case LVA = 'LVA'; // Latvia
    case MAC = 'MAC'; // Macao
    case MAF = 'MAF'; // Saint Martin (French part)
    case MAR = 'MAR'; // Morocco
    case MCO = 'MCO'; // Monaco
    case MDA = 'MDA'; // Moldova
    case MDG = 'MDG'; // Madagascar
    case MDV = 'MDV'; // Maldives
    case MEX = 'MEX'; // Mexico
    case MHL = 'MHL'; // Marshall Islands
    case MKD = 'MKD'; // North Macedonia
    case MLI = 'MLI'; // Mali
    case MLT = 'MLT'; // Malta
    case MMR = 'MMR'; // Myanmar
    case MNE = 'MNE'; // Montenegro
    case MNG = 'MNG'; // Mongolia
    case MNP = 'MNP'; // Northern Mariana Islands
    case MOZ = 'MOZ'; // Mozambique
    case MRT = 'MRT'; // Mauritania
    case MSR = 'MSR'; // Montserrat
    case MTQ = 'MTQ'; // Martinique
    case MUS = 'MUS'; // Mauritius
    case MWI = 'MWI'; // Malawi
    case MYS = 'MYS'; // Malaysia
    case MYT = 'MYT'; // Mayotte
    case NAM = 'NAM'; // Namibia
    case NCL = 'NCL'; // New Caledonia
    case NER = 'NER'; // Niger
    case NFK = 'NFK'; // Norfolk Island
    case NGA = 'NGA'; // Nigeria
    case NIC = 'NIC'; // Nicaragua
    case NIU = 'NIU'; // Niue
    case NLD = 'NLD'; // Netherlands
    case NOR = 'NOR'; // Norway
    case NPL = 'NPL'; // Nepal
    case NRU = 'NRU'; // Nauru
    case NZL = 'NZL'; // New Zealand
    case OMN = 'OMN'; // Oman
    case PAK = 'PAK'; // Pakistan
    case PAN = 'PAN'; // Panama
    case PCN = 'PCN'; // Pitcairn
    case PER = 'PER'; // Peru
    case PHL = 'PHL'; // Philippines
    case PLW = 'PLW'; // Palau
    case PNG = 'PNG'; // Papua New Guinea
    case POL = 'POL'; // Poland
    case PRI = 'PRI'; // Puerto Rico
    case PRK = 'PRK'; // Korea, Democratic People's Republic of
    case PRT = 'PRT'; // Portugal
    case PRY = 'PRY'; // Paraguay
    case PSE = 'PSE'; // Palestine, State of
    case PYF = 'PYF'; // French Polynesia
    case QAT = 'QAT'; // Qatar
    case REU = 'REU'; // Réunion
    case ROU = 'ROU'; // Romania
    case RUS = 'RUS'; // Russian Federation
    case RWA = 'RWA'; // Rwanda
    case SAU = 'SAU'; // Saudi Arabia
    case SDN = 'SDN'; // Sudan
    case SEN = 'SEN'; // Senegal
    case SGP = 'SGP'; // Singapore
    case SGS = 'SGS'; // South Georgia and the South Sandwich Islands
    case SHN = 'SHN'; // Saint Helena, Ascension and Tristan da Cunha
    case SJM = 'SJM'; // Svalbard and Jan Mayen
    case SLB = 'SLB'; // Solomon Islands
    case SLE = 'SLE'; // Sierra Leone
    case SLV = 'SLV'; // El Salvador
    case SMR = 'SMR'; // San Marino
    case SOM = 'SOM'; // Somalia
    case SPM = 'SPM'; // Saint Pierre and Miquelon
    case SRB = 'SRB'; // Serbia
    case SSD = 'SSD'; // South Sudan
    case STP = 'STP'; // Sao Tome and Principe
    case SUR = 'SUR'; // Suriname
    case SVK = 'SVK'; // Slovakia
    case SVN = 'SVN'; // Slovenia
    case SWE = 'SWE'; // Sweden
    case SWZ = 'SWZ'; // Eswatini
    case SXM = 'SXM'; // Sint Maarten (Dutch part)
    case SYC = 'SYC'; // Seychelles
    case SYR = 'SYR'; // Syrian Arab Republic
    case TCA = 'TCA'; // Turks and Caicos Islands
    case TCD = 'TCD'; // Chad
    case TGO = 'TGO'; // Togo
    case THA = 'THA'; // Thailand
    case TJK = 'TJK'; // Tajikistan
    case TKL = 'TKL'; // Tokelau
    case TKM = 'TKM'; // Turkmenistan
    case TLS = 'TLS'; // Timor-Leste
    case TON = 'TON'; // Tonga
    case TTO = 'TTO'; // Trinidad and Tobago
    case TUN = 'TUN'; // Tunisia
    case TUR = 'TUR'; // Türkiye
    case TUV = 'TUV'; // Tuvalu
    case TWN = 'TWN'; // Taiwan
    case TZA = 'TZA'; // Tanzania
    case UGA = 'UGA'; // Uganda
    case UKR = 'UKR'; // Ukraine
    case UMI = 'UMI'; // United States Minor Outlying Islands
    case URY = 'URY'; // Uruguay
    case USA = 'USA'; // United States of America
    case UZB = 'UZB'; // Uzbekistan
    case VAT = 'VAT'; // Holy See
    case VCT = 'VCT'; // Saint Vincent and the Grenadines
    case VEN = 'VEN'; // Venezuela
    case VGB = 'VGB'; // Virgin Islands (British)
    case VIR = 'VIR'; // Virgin Islands (U.S.)
    case VNM = 'VNM'; // Viet Nam
    case VUT = 'VUT'; // Vanuatu
    case WLF = 'WLF'; // Wallis and Futuna
    case WSM = 'WSM'; // Samoa
    case YEM = 'YEM'; // Yemen
    case ZAF = 'ZAF'; // South Africa
    case ZMB = 'ZMB'; // Zambia
    case ZWE = 'ZWE'; // Zimbabwe
    case OTH = 'OTH'; // Others
    case UNK = 'UNK'; // Unknown

    public function getFullName(): string
    {
        return match ($this) {
            self::ABW => 'Aruba',
            self::AFG => 'Afghanistan',
            self::AGO => 'Angola',
            self::AIA => 'Anguilla',
            self::ALA => 'Åland Islands',
            self::ALB => 'Albania',
            self::AND => 'Andorra',
            self::ARE => 'United Arab Emirates',
            self::ARG => 'Argentina',
            self::ARM => 'Armenia',
            self::ASM => 'American Samoa',
            self::ATA => 'Antarctica',
            self::ATF => 'French Southern Territories',
            self::ATG => 'Antigua and Barbuda',
            self::AUS => 'Australia',
            self::AUT => 'Austria',
            self::AZE => 'Azerbaijan',
            self::BDI => 'Burundi',
            self::BEL => 'Belgium',
            self::BEN => 'Benin',
            self::BES => 'Bonaire, Sint Eustatius and Saba',
            self::BFA => 'Burkina Faso',
            self::BGD => 'Bangladesh',
            self::BGR => 'Bulgaria',
            self::BHR => 'Bahrain',
            self::BHS => 'Bahamas',
            self::BIH => 'Bosnia and Herzegovina',
            self::BLM => 'Saint Barthélemy',
            self::BLR => 'Belarus',
            self::BLZ => 'Belize',
            self::BMU => 'Bermuda',
            self::BOL => 'Bolivia',
            self::BRA => 'Brazil',
            self::BRB => 'Barbados',
            self::BRN => 'Brunei Darussalam',
            self::BTN => 'Bhutan',
            self::BVT => 'Bouvet Island',
            self::BWA => 'Botswana',
            self::CAF => 'Central African Republic',
            self::CAN => 'Canada',
            self::CCK => 'Cocos (Keeling) Islands',
            self::CHE => 'Switzerland',
            self::CHL => 'Chile',
            self::CHN => 'China',
            self::CIV => 'Côte d\'Ivoire',
            self::CMR => 'Cameroon',
            self::COD => 'Congo, Democratic Republic of the',
            self::COG => 'Congo',
            self::COK => 'Cook Islands',
            self::COL => 'Colombia',
            self::COM => 'Comoros',
            self::CPV => 'Cabo Verde',
            self::CRI => 'Costa Rica',
            self::CUB => 'Cuba',
            self::CUW => 'Curaçao',
            self::CXR => 'Christmas Island',
            self::CYM => 'Cayman Islands',
            self::CYP => 'Cyprus',
            self::CZE => 'Czechia',
            self::DEU => 'Germany',
            self::DJI => 'Djibouti',
            self::DMA => 'Dominica',
            self::DNK => 'Denmark',
            self::DOM => 'Dominican Republic',
            self::DZA => 'Algeria',
            self::ECU => 'Ecuador',
            self::EGY => 'Egypt',
            self::ERI => 'Eritrea',
            self::ESH => 'Western Sahara',
            self::ESP => 'Spain',
            self::EST => 'Estonia',
            self::ETH => 'Ethiopia',
            self::FIN => 'Finland',
            self::FJI => 'Fiji',
            self::FLK => 'Falkland Islands (Malvinas)',
            self::FRA => 'France',
            self::FRO => 'Faroe Islands',
            self::FSM => 'Micronesia',
            self::GAB => 'Gabon',
            self::GBR => 'United Kingdom',
            self::GEO => 'Georgia',
            self::GGY => 'Guernsey',
            self::GHA => 'Ghana',
            self::GIB => 'Gibraltar',
            self::GIN => 'Guinea',
            self::GLP => 'Guadeloupe',
            self::GMB => 'Gambia',
            self::GNB => 'Guinea-Bissau',
            self::GNQ => 'Equatorial Guinea',
            self::GRC => 'Greece',
            self::GRD => 'Grenada',
            self::GRL => 'Greenland',
            self::GTM => 'Guatemala',
            self::GUF => 'French Guiana',
            self::GUM => 'Guam',
            self::GUY => 'Guyana',
            self::HKG => 'Hong Kong',
            self::HMD => 'Heard Island and McDonald Islands',
            self::HND => 'Honduras',
            self::HRV => 'Croatia',
            self::HTI => 'Haiti',
            self::HUN => 'Hungary',
            self::IDN => 'Indonesia',
            self::IMN => 'Isle of Man',
            self::IND => 'India',
            self::IOT => 'British Indian Ocean Territory',
            self::IRL => 'Ireland',
            self::IRN => 'Iran',
            self::IRQ => 'Iraq',
            self::ISL => 'Iceland',
            self::ISR => 'Israel',
            self::ITA => 'Italy',
            self::JAM => 'Jamaica',
            self::JEY => 'Jersey',
            self::JOR => 'Jordan',
            self::JPN => 'Japan',
            self::KAZ => 'Kazakhstan',
            self::KEN => 'Kenya',
            self::KGZ => 'Kyrgyzstan',
            self::KHM => 'Cambodia',
            self::KIR => 'Kiribati',
            self::KNA => 'Saint Kitts and Nevis',
            self::KOR => 'Korea, Republic of',
            self::KWT => 'Kuwait',
            self::LAO => 'Lao People\'s Democratic Republic',
            self::LBN => 'Lebanon',
            self::LBR => 'Liberia',
            self::LBY => 'Libya',
            self::LCA => 'Saint Lucia',
            self::LIE => 'Liechtenstein',
            self::LKA => 'Sri Lanka',
            self::LSO => 'Lesotho',
            self::LTU => 'Lithuania',
            self::LUX => 'Luxembourg',
            self::LVA => 'Latvia',
            self::MAC => 'Macao',
            self::MAF => 'Saint Martin (French part)',
            self::MAR => 'Morocco',
            self::MCO => 'Monaco',
            self::MDA => 'Moldova',
            self::MDG => 'Madagascar',
            self::MDV => 'Maldives',
            self::MEX => 'Mexico',
            self::MHL => 'Marshall Islands',
            self::MKD => 'North Macedonia',
            self::MLI => 'Mali',
            self::MLT => 'Malta',
            self::MMR => 'Myanmar',
            self::MNE => 'Montenegro',
            self::MNG => 'Mongolia',
            self::MNP => 'Northern Mariana Islands',
            self::MOZ => 'Mozambique',
            self::MRT => 'Mauritania',
            self::MSR => 'Montserrat',
            self::MTQ => 'Martinique',
            self::MUS => 'Mauritius',
            self::MWI => 'Malawi',
            self::MYS => 'Malaysia',
            self::MYT => 'Mayotte',
            self::NAM => 'Namibia',
            self::NCL => 'New Caledonia',
            self::NER => 'Niger',
            self::NFK => 'Norfolk Island',
            self::NGA => 'Nigeria',
            self::NIC => 'Nicaragua',
            self::NIU => 'Niue',
            self::NLD => 'Netherlands',
            self::NOR => 'Norway',
            self::NPL => 'Nepal',
            self::NRU => 'Nauru',
            self::NZL => 'New Zealand',
            self::OMN => 'Oman',
            self::PAK => 'Pakistan',
            self::PAN => 'Panama',
            self::PCN => 'Pitcairn',
            self::PER => 'Peru',
            self::PHL => 'Philippines',
            self::PLW => 'Palau',
            self::PNG => 'Papua New Guinea',
            self::POL => 'Poland',
            self::PRI => 'Puerto Rico',
            self::PRK => 'Korea, Democratic People\'s Republic of',
            self::PRT => 'Portugal',
            self::PRY => 'Paraguay',
            self::PSE => 'Palestine, State of',
            self::PYF => 'French Polynesia',
            self::QAT => 'Qatar',
            self::REU => 'Réunion',
            self::ROU => 'Romania',
            self::RUS => 'Russian Federation',
            self::RWA => 'Rwanda',
            self::SAU => 'Saudi Arabia',
            self::SDN => 'Sudan',
            self::SEN => 'Senegal',
            self::SGP => 'Singapore',
            self::SGS => 'South Georgia and the South Sandwich Islands',
            self::SHN => 'Saint Helena, Ascension and Tristan da Cunha',
            self::SJM => 'Svalbard and Jan Mayen',
            self::SLB => 'Solomon Islands',
            self::SLE => 'Sierra Leone',
            self::SLV => 'El Salvador',
            self::SMR => 'San Marino',
            self::SOM => 'Somalia',
            self::SPM => 'Saint Pierre and Miquelon',
            self::SRB => 'Serbia',
            self::SSD => 'South Sudan',
            self::STP => 'Sao Tome and Principe',
            self::SUR => 'Suriname',
            self::SVK => 'Slovakia',
            self::SVN => 'Slovenia',
            self::SWE => 'Sweden',
            self::SWZ => 'Eswatini',
            self::SXM => 'Sint Maarten (Dutch part)',
            self::SYC => 'Seychelles',
            self::SYR => 'Syrian Arab Republic',
            self::TCA => 'Turks and Caicos Islands',
            self::TCD => 'Chad',
            self::TGO => 'Togo',
            self::THA => 'Thailand',
            self::TJK => 'Tajikistan',
            self::TKL => 'Tokelau',
            self::TKM => 'Turkmenistan',
            self::TLS => 'Timor-Leste',
            self::TON => 'Tonga',
            self::TTO => 'Trinidad and Tobago',
            self::TUN => 'Tunisia',
            self::TUR => 'Türkiye',
            self::TUV => 'Tuvalu',
            self::TWN => 'Taiwan',
            self::TZA => 'Tanzania',
            self::UGA => 'Uganda',
            self::UKR => 'Ukraine',
            self::UMI => 'United States Minor Outlying Islands',
            self::URY => 'Uruguay',
            self::USA => 'United States of America',
            self::UZB => 'Uzbekistan',
            self::VAT => 'Holy See',
            self::VCT => 'Saint Vincent and the Grenadines',
            self::VEN => 'Venezuela',
            self::VGB => 'Virgin Islands (British)',
            self::VIR => 'Virgin Islands (U.S.)',
            self::VNM => 'Viet Nam',
            self::VUT => 'Vanuatu',
            self::WLF => 'Wallis and Futuna',
            self::WSM => 'Samoa',
            self::YEM => 'Yemen',
            self::ZAF => 'South Africa',
            self::ZMB => 'Zambia',
            self::ZWE => 'Zimbabwe',
            self::OTH => 'Others',
            self::UNK => 'Unknown',
        };
    }
}
