<?php

namespace Enums;

enum OptimizationGoal: string
{
    case APP_INSTALLS = 'APP_INSTALLS';
    case AD_RECALL_LIFT = 'AD_RECALL_LIFT';
    case CLICKS = 'CLICKS';
    case ENGAGED_USERS = 'ENGAGED_USERS';
    case EVENT_RESPONSES = 'EVENT_RESPONSES';
    case IMPRESSIONS = 'IMPRESSIONS';
    case LANDING_PAGE_VIEWS = 'LANDING_PAGE_VIEWS';
    case LEAD_GENERATION = 'LEAD_GENERATION';
    case LINK_CLICKS = 'LINK_CLICKS';
    case NONE = 'NONE';
    case OFFSITE_CONVERSIONS = 'OFFSITE_CONVERSIONS';
    case PAGE_LIKES = 'PAGE_LIKES';
    case POST_ENGAGEMENT = 'POST_ENGAGEMENT';
    case QUALITY_LEAD = 'QUALITY_LEAD';
    case REACH = 'REACH';
    case REPLIES = 'REPLIES';
    case SOCIAL_IMPRESSIONS = 'SOCIAL_IMPRESSIONS';
    case THRUPLAY = 'THRUPLAY';
    case VALUE = 'VALUE';
    case VISIT_INSTAGRAM_PROFILE = 'VISIT_INSTAGRAM_PROFILE';
    case PROFILE_VISITS = 'PROFILE_VISITS';
    case PROFILE_VISIT = 'PROFILE_VISIT';
    case CONVERSATIONS = 'CONVERSATIONS';
}
