project: '${PROJECT_NAME:-apis-hub}'
timezone: '${APP_TIMEZONE:-America/Caracas}'
debug: true
jobs:
  timeout_hours: 12
analytics:
  cache_raw_metrics: false
  marketing_debug_logs: false
cron:
  entities_hour: 2
  entities_minute: 0
  recent_hour: 5
  recent_minute: 0
